name: aplearn_group14
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  firebase_admin: ^0.1.2+1
  firebase_storage: ^3.1.6
  timeago: ^2.0.21
  image_picker: ^0.6.1+11
  chewie: ^0.9.10
  path: ^1.6.4
  path_provider: ^1.1.0
  flutter_dotenv: ^2.0.3
  flutter_ffmpeg: ^0.2.10
  video_player: ^0.10.8+1
  transparent_image: ^1.0.0
  filesize: ^1.0.4
  flushbar: ^1.9.1
  provider: ^4.0.5
  flutter_spinkit: "^4.1.2"
  url_launcher: ^5.4.11
  stripe_payment: ^1.0.7
  cloud_functions: ^0.5.0
  splashscreen: ^1.2.0
  uuid: ^2.0.4
  loading: ^1.0.2
  charts_flutter: ^0.9.0
  intl: ^0.16.0
  responsive_container: ^0.0.1
  auto_size_text: ^1.1.0
  carousel_slider: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background/bg1.jpg
    - assets/images/background/bg2.jpg
    - assets/images/icon/acaIcon.png
    - assets/images/icon/alterIcon.png
    - assets/images/icon/bioIcon.png
    - assets/images/icon/chemIcon.png
    - assets/images/icon/drawIcon.png
    - assets/images/icon/guitarIcon.png
    - assets/images/icon/math-highIcon.png
    - assets/images/icon/math-midIcon.png
    - assets/images/icon/phyIcon.png
    - assets/images/icon/sciIcon.png
    - assets/images/news/donationPage.png
    - assets/images/news/newsHire.png
    - assets/images/news/newsSubject.png
    - assets/images/news/newsVote.png
    - assets/images/news/profilePage.png
    - assets/images/news/editProfilePage.png
    - assets/images/news/votePage.png
    - assets/images/news/homeNewsHire.png
    - assets/images/news/homeNewsSubject.png
    - assets/images/news/homeNewsVote.jpg
    - assets/images/news/addCourse.png
    - assets/images/picture/academicLearning.png
    - assets/images/picture/alternativeLearning.jpg
    - assets/images/picture/donate.jpg
    - assets/images/picture/vote.png
    - assets/images/picture/school.jpg
    - assets/images/title/acaTitle.png
    - assets/images/title/alterTitle.png
    - assets/images/title/bioTitle.png
    - assets/images/title/chemTitle.png
    # - assets/images/title/drawIcon.png
    - assets/images/title/guitarTitle.png
    - assets/images/title/math-highTitle.png
    - assets/images/title/math-midTitle.png
    - assets/images/title/phyTitle.png
    # - assets/images/title/sciIcon.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
